# Generated by Django 3.2 on 2021-05-03 00:54

import FIRSTAPPLICATION.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default=FIRSTAPPLICATION.models.random_str, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(default=FIRSTAPPLICATION.models.random_id, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default=FIRSTAPPLICATION.models.random_id, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default=FIRSTAPPLICATION.models.random_str, max_length=50),
        ),
    ]
