# Generated by Django 3.2 on 2021-05-03 00:56

import FIRSTAPPLICATION.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0002_auto_20210502_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(default=FIRSTAPPLICATION.models.random_str, max_length=10),
        ),
    ]
